### ISSUE TITLE
No blank option available 

### ISSUE THREAD

**Issue by bramwillemse** [stormuk/Gravity-Forms-ACF-Field#14]
I'm using v1.0.0 and ACF Pro 5.1.7 on a customer website, but since an update to ACF Pro I seem not to have the option of a blank selection anymore.

Would be great if this could get fixed.. Thx in advance!

**Comment by jonahcoyote** [comment]
I created my own fork and added a quick hack for a null value: https://github.com/jonahcoyote/Gravity-Forms-ACF-Field/blob/master/gravity_forms-v5.php - I hope that helps others!

**Comment by Marcoevich** [comment]
This plugin just got a few major updates in the last few days. Blank selection should also work now :)

**Comment by bramwillemse** [comment]
Great stuff, thx for the heads up!
